# Generated by Django 3.1.7 on 2021-02-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'Deutsch'), ('it', 'Italian')], default='en', max_length=2),
        ),
    ]
